import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="containergrid justify-items-stretch bg-amber-50">
        <div className="h-40"></div>
        <div className="justify-self-center">{children}</div>
      </body>
    </html>
  )
}
